# File: configmaps.yaml

# ConfigMap for the main container
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main-config
data:
  nginx-main.conf: |
    server {
        listen 80;

        # Root directory for the main container
        root /usr/share/nginx/html;

        # Default index page
        index index.html;

        # Proxy requests to `/Aldi/` to the second container (aldi-service)
        location /Aldi/ {
            proxy_pass http://aldi-service.default.svc.cluster.local;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Disable caching
            proxy_buffering off;
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }

        # Serve all other requests directly from the main container
        location / {
            try_files $uri $uri/ =404;
        }
    }

---

# ConfigMap for the Aldi container
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-aldi-config
data:
  nginx-aldi.conf: |
    server {
        listen 80;

        # Root directory
        root /usr/share/nginx/html;

        # Default page for Aldi
        index Aldi/watchlater.html;

        # Serve all files normally
        location / {
            try_files $uri $uri/ =404;
        }
    }
